<script context = "module">

   export let filterfunc=(vidId)=> {ALL_VIDEOS.find((e) => e.id ==vidId)};
  

  export const ONE_VIDEO = {
    id: "30-tambellini",
    link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-tambellini.mp4",
    title: "Inauguration '81 by Aldo Tambellini",
    director: "",
    duration: 30,
  };
  
  export const ALL_VIDEOS = [
    {
      id: "30-tambellini",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-tambellini.mp4",
      title: "Inauguration '81 by Aldo Tambellini",
      director: "",
      duration: 30,
    },
    {
      id: "15-iggipooped-1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-iggipooped-1.mp4",
      title: "Iggy Pooped #1 By Jack Greer",
      director: "",
      duration: 15,
    },
    {
      id: "15-iggipooped-2",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-iggipooped-2.mp4",
      title: "Iggy Pooped #2 By Jack Greer",
      director: "",
      duration: 15,
    },
    {
      id: "15-iggipooped-3",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-iggipooped-3.mp4",
      title: "Iggy Pooped #3 By Jack Greer",
      director: "",
      duration: 15,
    },
    {
      id: "15-iggipooped-4",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-iggipooped-4.mp4",
      title: "Iggy Pooped #4 By Jack Greer",
      director: "",
      duration: 15,
    },
    {
      id: "15-nycNL",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-nycNL.mp4",
      title: "NYC Video Newsletters by Peter Sutherland",
      director: "",
      duration: 15,
    },
    {
      id: "30-CARTOONS",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-CARTOONS.mp4",
      title: "Cartoons #1 by Tommi",
      director: "",
      duration: 30,
    },
    {
      id: "30-MUSICSHOW",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-MUSICSHOW.mp4",
      title: "Music Show #1 by Tommi",
      director: "",
      duration: 30,
    },
    {
      id: "60-hourglass",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-hourglass.mp4",
      title: "Hour Glass by Tommi",
      director: "",
      duration: 60,
    },
    {
      id: "60-gs_foundshit_v1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-gs_foundshit_v1.mp4",
      title: "G's found shit 1",
      director: "",
      duration: 60,
    },
    {
      id: "15-gs_foundshit_v2",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-gs_foundshit_v2.mp4",
      title: "G's found shit 2",
      director: "",
      duration: 15,
    },
    {
      id: "15-gs_foundshit_v3",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-gs_foundshit_v3.mp4",
      title: "G's found shit 3",
      director: "",
      duration: 15,
    },
    {
      id: "60-gfoundshit-V4",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-gfoundshit-V4.mp4",
      title: "G's found shit 4",
      director: "",
      duration: 60,
    },
    {
      id: "60-holo",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-holo.mp4",
      title: "Holocaust Interviews by Brian Riemer & Emerson Rosenthal",
      director: "",
      duration: 60,
    },
    {
      id: "60-intimacy",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-intimacy.mp4",
      title: "Intimacy By Emerson",
      director: "",
      duration: 60,
    },
    {
      id: "45-tv3wt",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/45-tv3wt.mp4",
      title: "The Mayor of Montemilone by Adam Curtis",
      director: "",
      duration: 45,
    },
    {
      id: "15-stinkys-v1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-stinkys-v1.mp4",
      title: "Stinky Streets Video Zine by Hamburger Eyes",
      director: "",
      duration: 15,
    },
    {
      id: "60-SOHOVISION",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-SOHOVISION.mp4",
      title: "Soho Vision By Georgia",
      director: "",
      duration: 60,
    },
    {
      id: "15-SMTB",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-SMTB.mp4",
      title: "Show Me The Body: Live Under the Manhattan Bridge",
      director: "",
      duration: 15,
    },
    {
      id: "15-marty_tzonev",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-marty_tzonev.mp4",
      title: "Transparency By Marty Tzonev",
      director: "",
      duration: 15,
    },
    {
      id: "15-rick",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-rick.mp4",
      title: "A Taste of Rick Swenson",
      director: "",
      duration: 15,
    },
    {
      id: "60-chumbivilcas",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-chumbivilcas.mp4",
      title: "Chumbivilcas Stringout by Santiago Stelley",
      director: "",
      duration: 60,
    },
    {
      id: "15-GDS_perfectweights",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-GDS_perfectweights.mp4",
      title: "Perfect Weights/Vectors By Giorgio Di Salvo",
      director: "",
      duration: 15,
    },
    {
      id: "30-newsstand",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-newsstand.mp4",
      title: "The Newstand",
      director: "",
      duration: 30,
    },
    {
      id: "30-TVTV1-17",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-TVTV1-17.mp4",
      title: "TVTV 1-17 By Nick Atkins",
      director: "",
      duration: 30,
    },
    {
      id: "15-TVTV18-25",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-TVTV18-25.mp4",
      title: "TVTV 18-25 By Nick Atkins",
      director: "",
      duration: 15,
    },
    {
      id: "15-TVTV26-31",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-TVTV26-31.mp4",
      title: "TVTV 26-31 By Nick Atkins",
      director: "",
      duration: 15,
    },
    {
      id: "15-squillacciotti1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-squillacciotti1.mp4",
      title:
        "Casi la mitad de la historia/Far from where we came By G. Squillacciotti",
      director: "",
      duration: 15,
    },
    {
      id: "15-triloTLU",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-triloTLU.mp4",
      title: "Trilogia della Morte/To Lie Under By Lele Saveri",
      director: "",
      duration: 15,
    },
    {
      id: "45-ANGELADAVIS",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/45-ANGELADAVIS.mp4",
      title: "Angela Davis interview",
      director: "",
      duration: 45,
    },
    {
      id: "60-COMMERCIAL",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-COMMERCIAL.mp4",
      title: "Commercial Compilation",
      director: "",
      duration: 60,
    },
    {
      id: "60-LOSANGELES",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-LOSANGELES.mp4",
      title: "Los Angeles",
      director: "",
      duration: 60,
    },
    {
      id: "60-MasteryOfSpace",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-MasteryOfSpace.mp4",
      title: "Mastery of Space",
      director: "",
      duration: 60,
    },
    {
      id: "15-TOPOLOGY",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-TOPOLOGY.mp4",
      title: "Topology",
      director: "",
      duration: 15,
    },
    {
      id: "60-SONATA",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-SONATA.mp4",
      title: "Sonata",
      director: "",
      duration: 60,
    },
    {
      id: "15-After119_1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-After119_1.mp4",
      title: "After 11-9, November 10th 2016, New York City",
      director: "",
      duration: 15,
    },
    {
      id: "60-After11_9_JFK",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-After11_9_JFK.mp4",
      title: "After 11-9, January 29th  2017, JFK",
      director: "",
      duration: 60,
    },
    {
      id: "15-AFTER119WASHINGTONSQUAREPARK",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-AFTER119WASHINGTONSQUAREPARK.mp4",
      title: "After 11-9, February 11th  2017, Washington Square Park NYC",
      director: "",
      duration: 15,
    },
    {
      id: "15-after11-9_wahingtonDC",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-after11-9_wahingtonDC.mp4",
      title: "After 11-9, January 21st  2017, Washington DC",
      director: "",
      duration: 15,
    },
    {
      id: "15-gslimey_ep1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-gslimey_ep1.mp4",
      title: "G Slimey's HELL WORLD #1",
      director: "",
      duration: 15,
    },
    {
      id: "15-gslimey_ep2",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-gslimey_ep2.mp4",
      title: "G Slimey's HELL WORLD #2",
      director: "",
      duration: 15,
    },
    {
      id: "30-gslimey_ep3",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-gslimey_ep3.mp4",
      title: "G Slimey's HELL WORLD #3 DARK WINGZ, DARK WORDZ",
      director: "",
      duration: 30,
    },
    {
      id: "60-Gslimey_LetsPlay1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-Gslimey_LetsPlay1.mp4",
      title: "G_Slimey's LETS PLAY 1",
      director: "",
      duration: 60,
    },
    {
      id: "60-Gslimey_Letsplay2",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-Gslimey_Letsplay2.mp4",
      title: "G_Slimey's LET'S PLAY 2 BREATH OF FIRE 3 (CLIMATE CHANGE REMIX",
      director: "",
      duration: 60,
    },
    {
      id: "60-Gslimey_Letsplay3",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-Gslimey_Letsplay3.mp4",
      title:
        "G_Slimey's LET'S PLAY 3 PILLARS OF ETERNITY PART 1 (DARK AMBIENT JPOP REMIX",
      director: "",
      duration: 60,
    },
    {
      id: "15-GslimeyHellWorld5",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-GslimeyHellWorld5.mp4",
      title: "G_SLIMEY'S HELL WORLD EPISODE 5: MY DAD JUST GOT INTO NARUTO",
      director: "",
      duration: 15,
    },
    {
      id: "30-8BALLSHORTIES_EPISODE1_FACTS",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-8BALLSHORTIES_EPISODE1_FACTS.mp4",
      title: "Shorties#1 by FACTS",
      director: "",
      duration: 30,
    },
    {
      id: "60-8BALLSHORTIES_Episode2_JAMES&TED",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-8BALLSHORTIES_Episode2_JAMES&TED.mp4",
      title: "Shorties#2 Curated by James Watson & Ted Gerike",
      director: "",
      duration: 60,
    },
    {
      id: "30-8BALLSHORTIES_Episode3_MISC",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-8BALLSHORTIES_Episode3_MISC.mp4",
      title: "Shorties#3 Curated by Vicky Lim & Sam Mink",
      director: "",
      duration: 30,
    },
    {
      id: "60-8BALLSHORTIES_EPISODE4_AMERICANJUGGALO",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-8BALLSHORTIES_EPISODE4_AMERICANJUGGALO.mp4",
      title: "Shorties#4: American Juggalo I & II by Sean Dunne",
      director: "",
      duration: 60,
    },
    {
      id: "60-8BALLSHORTIES_EPISODE5_SEANDUNNEMEDLEY",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-8BALLSHORTIES_EPISODE5_SEANDUNNEMEDLEY.mp4",
      title: "Shorties#5 by Sean Dunne",
      director: "",
      duration: 60,
    },
    {
      id: "45-8BALLSHORTIES_6",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/45-8BALLSHORTIES_6.mp4",
      title: "Shorties#6 by Renata Poljak",
      director: "",
      duration: 45,
    },
    {
      id: "30-8BALLSHORTIES_EPISODE7_FRANKIECARINO",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-8BALLSHORTIES_EPISODE7_FRANKIECARINO.mp4",
      title: "Shorties#7 by Frankie Carino",
      director: "",
      duration: 30,
    },
    {
      id: "15-GrandPrix_1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-GrandPrix_1.mp4",
      title: "Grand Prix by Caglar Kanzik",
      director: "",
      duration: 15,
    },
    {
      id: "15-hmartell_1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-hmartell_1.mp4",
      title: "carpool lane by Hayley Martell",
      director: "",
      duration: 15,
    },
    {
      id: "15-SISTERPIFF",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-SISTERPIFF.mp4",
      title: "15 minutes in heaven, hell and purgatory By Sister Piff",
      director: "",
      duration: 15,
    },
    {
      id: "15-Heatherhans_1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-Heatherhans_1.mp4",
      title:
        "Harmonizing Relationships & Empowering People to Excel and Radiate with Confidence by Heather Hans",
      director: "",
      duration: 15,
    },
    {
      id: "30-JackWedgeCompilation",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-JackWedgeCompilation.mp4",
      title: "Jack Wedge Compilation",
      director: "",
      duration: 30,
    },
    {
      id: "15-MannyAguif_EP1_GRAFF",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-MannyAguif_EP1_GRAFF.mp4",
      title: "GRAFF Ep 1 by Manny Aguif",
      director: "",
      duration: 15,
    },
    {
      id: "60-LawrenceLek_Sinofuturism",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-LawrenceLek_Sinofuturism.mp4",
      title: "Sinofuturism by Lawrence Lek",
      director: "",
      duration: 60,
    },
    {
      id: "15-MinisterAkinsCompliation",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-MinisterAkinsCompliation.mp4",
      title: "MinisterAkins Compliation",
      director: "",
      duration: 15,
    },
    {
      id: "30-MetadataLIVINGROOMTODAY",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-MetadataLIVINGROOMTODAY.mp4",
      title: "Metadata For #LIVINGROOMTODAY",
      director: "",
      duration: 30,
    },
    {
      id: "30-SLEEPYEYESLIVINGROOMTODAY",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-SLEEPYEYESLIVINGROOMTODAY.mp4",
      title: "Sleepyeyes For #LIVNGROOMTODAY",
      director: "",
      duration: 30,
    },
    {
      id: "15-PeppreAnn_2",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-PeppreAnn_2.mp4",
      title: "Adventures of Peppré Ann and Friends",
      director: "",
      duration: 15,
    },
    {
      id: "15-final33actuallyreal",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-final33actuallyreal.mp4",
      title: "33 signs you’re in a simulator #1",
      director: "",
      duration: 15,
    },
    {
      id: "15-33signsep2",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-33signsep2.mp4",
      title: "33 signs you’re in a simulator #2",
      director: "",
      duration: 15,
    },
    {
      id: "60-jpwfeedbackvisuals",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-jpwfeedbackvisuals.mp4",
      title: "JPW feedback visuals",
      director: "",
      duration: 60,
    },
    {
      id: "60-jpwextradontvisuals",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-jpwextradontvisuals.mp4",
      title: "JPW extra don't visuals",
      director: "",
      duration: 60,
    },
    {
      id: "30-LASOUFRIERE",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-LASOUFRIERE.mp4",
      title: "La Soufriere",
      director: "",
      duration: 30,
    },
    {
      id: "15-Aliciamersy1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-Aliciamersy1.mp4",
      title: "Alicia Mersy",
      director: "",
      duration: 15,
    },
    {
      id: "30-TonyChoySuttonSPAMDEATHGATE",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-TonyChoySuttonSPAMDEATHGATE.mp4",
      title: "SpamDeathGate by Tony Choy-Sutton",
      director: "",
      duration: 30,
    },
    {
      id: "15-TonyChoySuttonPARIS",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-TonyChoySuttonPARIS.mp4",
      title: "To Friends I Have Lost by Tony Choy-Sutton",
      director: "",
      duration: 15,
    },
    {
      id: "30-yw_noimage",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-yw_noimage.mp4",
      title: "No Image by Yemenwed",
      director: "",
      duration: 30,
    },
    {
      id: "30-DIRTCITYFLIXX_EP1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-DIRTCITYFLIXX_EP1.mp4",
      title: "DIRT CITY FLIXX",
      director: "",
      duration: 30,
    },
    {
      id: "15-tischabelow",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-tischabelow.mp4",
      title: "IF by Tisch Abelow & Dakotah Savage and Donkey_2 by Tisch Abelow",
      director: "",
      duration: 15,
    },
    {
      id: "15-TTSTHEATRE_EP1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-TTSTHEATRE_EP1.mp4",
      title: "TTS Theatre",
      director: "",
      duration: 15,
    },
    {
      id: "15-ECE_EP1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-ECE_EP1.mp4",
      title: "El Cuarto Elastico",
      director: "",
      duration: 15,
    },
    {
      id: "30-VIDEO_EMOTION_MIXTAPE_1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-VIDEO_EMOTION_MIXTAPE_1.mp4",
      title: "Video Emotion Mixtape by No Text Azienda",
      director: "",
      duration: 30,
    },
    {
      id: "45-SPIRITUAL_ENLARAGEMENT",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/45-SPIRITUAL_ENLARAGEMENT.mp4",
      title: "Spiritual Enlargement by Samuel Hindolo",
      director: "",
      duration: 45,
    },
    {
      id: "15-ARTHROPODA-POOKNEW",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-ARTHROPODA-POOKNEW.mp4",
      title: "Arthropoda / Poo Knew By 75 E Broadway",
      director: "",
      duration: 15,
    },
    {
      id: "15-POOKNEW-PHARAOHSSNAKE",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-POOKNEW-PHARAOHSSNAKE.mp4",
      title: "Poo Knew / Pharaoh's Snake By 75 E Broadway",
      director: "",
      duration: 15,
    },
    {
      id: "30-official_tourist",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-official_tourist.mp4",
      title: "Official Tourist",
      director: "",
      duration: 30,
    },
    {
      id: "15-clairechristerson_daisywild",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-clairechristerson_daisywild.mp4",
      title: "Videos by Daisy & Wild and Claire Christerson",
      director: "",
      duration: 15,
    },
    {
      id: "15-LeonardPeltierOglalaSiouxIndianTribe",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-LeonardPeltierOglalaSiouxIndianTribe.mp4",
      title: "Leonard Peltier and the Oglala Sioux Indian Tribe",
      director: "",
      duration: 15,
    },
    {
      id: "30-SFWAWhootyVideo",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-SFWAWhootyVideo.mp4",
      title: "A Whooty Video by Lindsay Dye",
      director: "",
      duration: 30,
    },
    {
      id: "30-XTheUnheardMusicDocumentary1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-XTheUnheardMusicDocumentary1.mp4",
      title: "X The Unheard Music Documentary part 1",
      director: "",
      duration: 30,
    },
    {
      id: "30-XTheUnheardMusicDocumentary2",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-XTheUnheardMusicDocumentary2.mp4",
      title: "X The Unheard Music Documentary part 2",
      director: "",
      duration: 30,
    },
    {
      id: "30-XTheUnheardMusicDocumentary3",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-XTheUnheardMusicDocumentary3.mp4",
      title: "X The Unheard Music Documentary part 3",
      director: "",
      duration: 30,
    },
    {
      id: "15-jonknox_Swampysdiary",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-jonknox_Swampysdiary.mp4",
      title: "Swampy’s Diary by Swampy",
      director: "",
      duration: 15,
    },
    {
      id: "15-Loreleiramirez_Milkshake",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-Loreleiramirez_Milkshake.mp4",
      title: "Milkshake by Lorelei Ramirez & Max Rosen",
      director: "",
      duration: 15,
    },
    {
      id: "15-miakerin_1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-miakerin_1.mp4",
      title: "Videos by Mia Kerin",
      director: "",
      duration: 15,
    },
    {
      id: "30-yw_becauseyourehere",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-yw_becauseyourehere.mp4",
      title: "The Because You're Here Show By Megha Barnabas",
      director: "",
      duration: 30,
    },
    {
      id: "45-yw_heavyflow",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/45-yw_heavyflow.mp4",
      title: "Heavy Flow By Yemenwed",
      director: "",
      duration: 45,
    },
    {
      id: "30-HenryAWallaceCommonManSpeech-JamilAbdullahAl-Amin",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-HenryAWallaceCommonManSpeech-JamilAbdullahAl-Amin.mp4",
      title: "Jamil Abdullah Al-Amin / Henry A Wallace's Common Man",
      director: "",
      duration: 30,
    },
    {
      id: "45_SHELBYSELLSSHOW_1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/45_SHELBYSELLSSHOW_1.mp4",
      title: "The Shelby Sells Show #1 By Shelby Sells",
      director: "",
      duration: 45,
    },
    {
      id: "15-colinhuggins",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-colinhuggins.mp4",
      title: "Colin Huggins",
      director: "",
      duration: 15,
    },
    {
      id: "30-NewWaveTheatre-01",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-NewWaveTheatre-01.mp4",
      title: "New Wave Theatre Ep.1",
      director: "",
      duration: 30,
    },
    {
      id: "30-NewWaveTheatre-02",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-NewWaveTheatre-02.mp4",
      title: "New Wave Theatre Ep.2",
      director: "",
      duration: 30,
    },
    {
      id: "30-NewWaveTheatre-03",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-NewWaveTheatre-03.mp4",
      title: "New Wave Theatre Ep.3",
      director: "",
      duration: 30,
    },
    {
      id: "15-NewWaveTheatre-04",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-NewWaveTheatre-04.mp4",
      title: "New Wave Theatre Ep.4",
      director: "",
      duration: 15,
    },
    {
      id: "30-DonaldDucksMathMagicLand",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-DonaldDucksMathMagicLand.mp4",
      title:
        "Donald Duck’s Mathemagic Land by Disney Education Animation Studios",
      director: "",
      duration: 30,
    },
    {
      id: "30-HelloKittysAliceInWonderland",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-HelloKittysAliceInWonderland.mp4",
      title: "Hello Kitty’s Alice In Wonderlandby Sanrio",
      director: "",
      duration: 30,
    },
    {
      id: "60-MarsAndBeyond",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-MarsAndBeyond.mp4",
      title: "Mars and Beyond by Disney Education Animation Studios",
      director: "",
      duration: 60,
    },
    {
      id: "30-TheKidsGuidetotheInternet",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-TheKidsGuidetotheInternet.mp4",
      title: "The Kids Guide to the Internet",
      director: "",
      duration: 30,
    },
    {
      id: "45-ManAndTheMoon",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/45-ManAndTheMoon.mp4",
      title: "Man and the Moon by Disney Education Animation Studios",
      director: "",
      duration: 45,
    },
    {
      id: "30-AnimationsJackWedge",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-AnimationsJackWedge.mp4",
      title: "Animations by Jack Wedge",
      director: "",
      duration: 30,
    },
    {
      id: "30-JaphyRiddle_BlockofVideos",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-JaphyRiddle_BlockofVideos.mp4",
      title: "Block of Videos by Japhy Riddle",
      director: "",
      duration: 30,
    },
    {
      id: "15-ChristinaAcevedo_OKdrown",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-ChristinaAcevedo_OKdrown.mp4",
      title: "OK drown by Christina Acevedo",
      director: "",
      duration: 15,
    },
    {
      id: "45-BLACKHISTORYMONTH_COLLAGEMIXTAPE",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/45-BLACKHISTORYMONTH_COLLAGEMIXTAPE.mp4",
      title: "CELEBRATING BLACK HISTORY MONTH: A VISUAL MIXTAPE",
      director: "",
      duration: 45,
    },
    {
      id: "60-ygfood-1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-ygfood-1.mp4",
      title: "YGFOOD#1",
      director: "",
      duration: 60,
    },
    {
      id: "60-YGFOOD2",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/60-YGFOOD2.mp4",
      title: "YGFOOD#2",
      director: "",
      duration: 60,
    },
    {
      id: "15-SOCKNECK_sowellhiaasen1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-SOCKNECK_sowellhiaasen1.mp4",
      title: "SOCK NECK by Sara Sowell & Hannah Hiaasen",
      director: "",
      duration: 15,
    },
    {
      id: "15-resistfascism_Petevoelker",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-resistfascism_Petevoelker.mp4",
      title: "Resist Fascism by Pete Voelker",
      director: "",
      duration: 15,
    },
    {
      id: "15-Ijustdontremeber_michaelbaur1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-Ijustdontremeber_michaelbaur1.mp4",
      title: "I JUST DONT REMEBER by Michael Baur",
      director: "",
      duration: 15,
    },
    {
      id: "15-DAPL",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-DAPL.mp4",
      title: "Deepstep come shining: water protector #1",
      director: "",
      duration: 15,
    },
    {
      id: "15-LAURA1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-LAURA1.mp4",
      title: "Standing Rock report #1 by Laura Hinman",
      director: "",
      duration: 15,
    },
    {
      id: "15-LAURA2",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-LAURA2.mp4",
      title: "Standing Rock report #2 by Laura Hinman",
      director: "",
      duration: 15,
    },
    {
      id: "15-LAURA3",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-LAURA3.mp4",
      title: "Standing Rock report #3 by Laura Hinman",
      director: "",
      duration: 15,
    },
    {
      id: "15-SPEAKINGOUTSPEECHESFROMSTANDINGROCK",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-SPEAKINGOUTSPEECHESFROMSTANDINGROCK.mp4",
      title: "SPEAKING OUT: SPEECHES FROM STANDING ROCK",
      director: "",
      duration: 15,
    },
    {
      id: "15-UNICORNMEDIADAPL",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-UNICORNMEDIADAPL.mp4",
      title: "STANDING ROCK: UNICORN MEDIA REPORT",
      director: "",
      duration: 15,
    },
    {
      id: "15-LELEnodapl1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-LELEnodapl1.mp4",
      title: "NO DAPL 2/22/2017 #1",
      director: "",
      duration: 15,
    },
    {
      id: "15-LELEnodapl2",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-LELEnodapl2.mp4",
      title: "NO DAPL 2/22/2017 #2",
      director: "",
      duration: 15,
    },
    {
      id: "15-LELEnodapl3",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-LELEnodapl3.mp4",
      title: "NO DAPL 2/22/2017 #3",
      director: "",
      duration: 15,
    },
    {
      id: "15-STANDINGROCKMIX",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-STANDINGROCKMIX.mp4",
      title: "Standing Rock Mixtape: Laura Hinman, Jessie Adler, Blazer",
      director: "",
      duration: 15,
    },
    {
      id: "15-thefront-1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-thefront-1.mp4",
      title: "The Front presents #1",
      director: "",
      duration: 15,
    },
    {
      id: "45-frictionalInchoate",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/45-frictionalInchoate.mp4",
      title: "Frictional by Inchoate",
      director: "",
      duration: 45,
    },
    {
      id: "30-FRANKENSTEINEYESIGHTEP1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-FRANKENSTEINEYESIGHTEP1.mp4",
      title:
        "THE SAVAGE YOUNG TATER BUG/TRACEY TRANCE/BLACK CHICKEN/FRANKENSTEIN EYESIGHT TV #1",
      director: "",
      duration: 30,
    },
    {
      id: "30-FRANKENSTEINEYESIGHTEP2",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-FRANKENSTEINEYESIGHTEP2.mp4",
      title: "FRANKENSTEIN EYESIGHT TV #2-LITTLE HOWLIN WOLF",
      director: "",
      duration: 30,
    },
    {
      id: "30-FrankensteinEyesight_Ep3",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-FrankensteinEyesight_Ep3.mp4",
      title: "FRANKENSTEIN EYESIGHT TV EPISODE 3-SEWN LEATHER-BUDDY BAG",
      director: "",
      duration: 30,
    },
    {
      id: "15-LarissaMinty_Americanbeauty_1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-LarissaMinty_Americanbeauty_1.mp4",
      title: "American Body by Larissa Minty",
      director: "",
      duration: 15,
    },
    {
      id: "15-Miakerin_Louise",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-Miakerin_Louise.mp4",
      title: "LOUISE: A film by Mia Kerin",
      director: "",
      duration: 15,
    },
    {
      id: "15-mleduc_sciencetv1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-mleduc_sciencetv1.mp4",
      title: "M Leduc's Science TV",
      director: "",
      duration: 15,
    },
    {
      id: "15-kurbjunki_sk8video",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-kurbjunki_sk8video.mp4",
      title: "Privado+The Kurb Junki Show by Kurb Junki",
      director: "",
      duration: 15,
    },
    {
      id: "30-LAMBB_50ShadesofMelanin",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-LAMBB_50ShadesofMelanin.mp4",
      title: "LAMBB Presents 50 Shades of Melanin",
      director: "",
      duration: 30,
    },
    {
      id: "30-Joshslater_4films_1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-Joshslater_4films_1.mp4",
      title: "4 Films by Josh Slater",
      director: "",
      duration: 30,
    },
    {
      id: "30-LordsofFun_1Father",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-LordsofFun_1Father.mp4",
      title: "The Lords of Fun #1: Father",
      director: "",
      duration: 30,
    },
    {
      id: "30-Lordsoffun_2Balls",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-Lordsoffun_2Balls.mp4",
      title: "The Lords of Fun #2: Balls",
      director: "",
      duration: 30,
    },
    {
      id: "30-Lordsoffun_3Catnog",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-Lordsoffun_3Catnog.mp4",
      title: "The Lords of Fun #3: Catnog",
      director: "",
      duration: 30,
    },
    {
      id: "30-Lordsoffun_4Brothers",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-Lordsoffun_4Brothers.mp4",
      title: "The Lords of Fun #4: Brothers",
      director: "",
      duration: 30,
    },
    {
      id: "30-Lordsoffun_5GypsyDypsy",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-Lordsoffun_5GypsyDypsy.mp4",
      title: "The Lords of Fun #5: Gypsy Dypsy",
      director: "",
      duration: 30,
    },
    {
      id: "30-Lordsoffun_6EverybodyPeesweb",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-Lordsoffun_6EverybodyPeesweb.mp4",
      title: "The Lords of Fun #6: Everybody Pees",
      director: "",
      duration: 30,
    },
    {
      id: "30-Lordsoffun_7",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-Lordsoffun_7.mp4",
      title: "The Lords of Fun #7: The Devil And Jeremy Flash",
      director: "",
      duration: 30,
    },
    {
      id: "30-Lordsoffun_8",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-Lordsoffun_8.mp4",
      title: "The Lords of Fun #8: Howard's House Part 1",
      director: "",
      duration: 30,
    },
    {
      id: "30-LordsofFun_9HowardsHousep2",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-LordsofFun_9HowardsHousep2.mp4",
      title: "The Lords of Fun #9: Howard's House Part 2",
      director: "",
      duration: 30,
    },
    {
      id: "30-LordsofFun_10UrineMyDreams1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-LordsofFun_10UrineMyDreams1.mp4",
      title: "The Lords of Fun #10: Urine My Dreams",
      director: "",
      duration: 30,
    },
    {
      id: "15-MyBuddyandKidSister_Lettucehead",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-MyBuddyandKidSister_Lettucehead.mp4",
      title: "Lettucehead by My Buddy & Kid Sister",
      director: "",
      duration: 15,
    },
    {
      id: "45-ANTARCTICA_TEBOTJIF",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/45-ANTARCTICA_TEBOTJIF.mp4",
      title: "Antarctica and TEBOTJIF",
      director: "",
      duration: 45,
    },
    {
      id: "15-GabrielleDeCaro_ForgetYourKitten",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-GabrielleDeCaro_ForgetYourKitten.mp4",
      title: "FORGET YOUR KITTEN by Gabrielle DeCaro",
      director: "",
      duration: 15,
    },
    {
      id: "15-CagilHarmandar_Shortfilms",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-CagilHarmandar_Shortfilms.mp4",
      title: "Cagil Harmandar: Short Films (2014-2016)",
      director: "",
      duration: 15,
    },
    {
      id: "15-coilinoconnell_ivehadthetimeofmylife",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-coilinoconnell_ivehadthetimeofmylife.mp4",
      title: "I've had the time of my life by Coilin O'Connell",
      director: "",
      duration: 15,
    },
    {
      id: "15-Dbaitloop_sarahodonaghue",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-Dbaitloop_sarahodonaghue.mp4",
      title: "dbaitloop by Sarah O'Donoghue",
      director: "",
      duration: 15,
    },
    {
      id: "30-masonwilson_rollcallvol1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-masonwilson_rollcallvol1.mp4",
      title: "Roll Call Vol. 1 by Mason Wilson",
      director: "",
      duration: 30,
    },
    {
      id: "45-betapictures_daisypark",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/45-betapictures_daisypark.mp4",
      title: "Beta Pictures Presents: Air Pop's Daisy Park",
      director: "",
      duration: 45,
    },
    {
      id: "15_dawnriddle_mtv12musicbliparchive",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15_dawnriddle_mtv12musicbliparchive.mp4",
      title: "MTV12 Music Blip Archive by Dawn Riddle",
      director: "",
      duration: 15,
    },
    {
      id: "15_ninadolores_ROCKFRESHTV1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15_ninadolores_ROCKFRESHTV1.mp4",
      title: "Rock Fresh TV Episode 1 by Nina Dolores",
      director: "",
      duration: 15,
    },
    {
      id: "45_Andrewstorrs_taterjeans",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/45_Andrewstorrs_taterjeans.mp4",
      title:
        "TRACEY TRANCE's RUNNIN & BOSSIN & THE SAVAGE YOUNG TATER BUG's JEANS by Andrew Storrs",
      director: "",
      duration: 45,
    },
    {
      id: "45_jorosenthal_jorosenthal_1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/45_jorosenthal_jorosenthal_1.mp4",
      title: "An Evening with Doctor Jo Rosenthal",
      director: "",
      duration: 45,
    },
    {
      id: "15_carolinenewton_3movements",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15_carolinenewton_3movements.mp4",
      title: "Movement Via Prompt 1, 2, & 3 by Caroline Newton",
      director: "",
      duration: 15,
    },
    {
      id: "15_realbigboys_1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15_realbigboys_1.mp4",
      title: "REAL BIG BOYS",
      director: "",
      duration: 15,
    },
    {
      id: "15-franbeltran_NYSalad1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-franbeltran_NYSalad1.mp4",
      title: "New York Salad #1 by Francesca Beltran",
      director: "",
      duration: 15,
    },
    {
      id: "15-franbeltran_NYSalad2",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-franbeltran_NYSalad2.mp4",
      title: "New York Salad #2 by Francesca Beltran",
      director: "",
      duration: 15,
    },
    {
      id: "15-thuto_studying",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-thuto_studying.mp4",
      title: "Studying by Thuto Durkac-Somo",
      director: "",
      duration: 15,
    },
    {
      id: "15-EmilyDavis_Musicvideos",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-EmilyDavis_Musicvideos.mp4",
      title: "EMTV Music Videos #1",
      director: "",
      duration: 15,
    },
    {
      id: "15-KellCasual_ShesCasual",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-KellCasual_ShesCasual.mp4",
      title: "She's Casual by Kell Casual",
      director: "",
      duration: 15,
    },
    {
      id: "15-RobFraebelTHEBIGDIRTYMIXTAPE",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-RobFraebelTHEBIGDIRTYMIXTAPE.mp4",
      title: "THE BIG DIRTY MIXTAPE",
      director: "",
      duration: 15,
    },
    {
      id: "45-JeffMertz_Slowburn1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/45-JeffMertz_Slowburn1.mp4",
      title: "Slow Burn by Jeff Mertz",
      director: "",
      duration: 45,
    },
    {
      id: "15-SCM_E1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-SCM_E1.mp4",
      title: "SURVEILLANCE CAMERA MAN Episode 1",
      director: "",
      duration: 15,
    },
    {
      id: "15-SCM_E2",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-SCM_E2.mp4",
      title: "SURVEILLANCE CAMERA MAN Episode 2",
      director: "",
      duration: 15,
    },
    {
      id: "15-SCM_E3",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-SCM_E3.mp4",
      title: "SURVEILLANCE CAMERA MAN Episode 3",
      director: "",
      duration: 15,
    },
    {
      id: "15-HowToWithJohnWilson_E01",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-HowToWithJohnWilson_E01.mp4",
      title: "HOW TO With John Wilson 1",
      director: "",
      duration: 15,
    },
    {
      id: "45-HowToWithJohnWilson_E02_HowSingle_onRealityTV",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/45-HowToWithJohnWilson_E02_HowSingle_onRealityTV.mp4",
      title: "HOW TO With John Wilson 2",
      director: "",
      duration: 45,
    },
    {
      id: "15-beatdetectives_1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-beatdetectives_1.mp4",
      title: "Beat Detectives: #1, by Aaron Anderson",
      director: "",
      duration: 15,
    },
    {
      id: "15-beatdetectives_2",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-beatdetectives_2.mp4",
      title: "Beat Detectives: #2, by Aaron Anderson",
      director: "",
      duration: 15,
    },
    {
      id: "15-beatdetectives_3",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-beatdetectives_3.mp4",
      title: "Beat Detectives: #3, by Aaron Anderson",
      director: "",
      duration: 15,
    },
    {
      id: "15-beatdetectives_4",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-beatdetectives_4.mp4",
      title: "Beat Detectives: #4, by Aaron Anderson",
      director: "",
      duration: 15,
    },
    {
      id: "15-beatdetectives_5",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-beatdetectives_5.mp4",
      title: "Beat Detectives: #5, by Aaron Anderson",
      director: "",
      duration: 15,
    },
    {
      id: "15-AlexOKeefe_Bandonthestreet1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-AlexOKeefe_Bandonthestreet1.mp4",
      title: "Band on the Street #1 ft PALEHOUND",
      director: "",
      duration: 15,
    },
    {
      id: "15-AlexOKeefe_Bandonthestreet2",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-AlexOKeefe_Bandonthestreet2.mp4",
      title: "Band on the Street #2 ft REPTAR",
      director: "",
      duration: 15,
    },
    {
      id: "15-AlexOKeefe_BandontheStreet3",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-AlexOKeefe_BandontheStreet3.mp4",
      title: "Band on the Street #3 ft Dads",
      director: "",
      duration: 15,
    },
    {
      id: "15-AlexOKeefe_Bandonthestreet4",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-AlexOKeefe_Bandonthestreet4.mp4",
      title: "Band on the Street #4 ft SCREAMING FEMALES",
      director: "",
      duration: 15,
    },
    {
      id: "45-DIALECTIC_1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/45-DIALECTIC_1.mp4",
      title: "The Dialectic Episode 1",
      director: "",
      duration: 45,
    },
    {
      id: "15-DialecticVignette1_5",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-DialecticVignette1_5.mp4",
      title: "The Dialectic: An Oscars Vignette",
      director: "",
      duration: 15,
    },
    {
      id: "15-RobertLeeGordon_shorts2014_2016",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-RobertLeeGordon_shorts2014_2016.mp4",
      title: "Robert Lee Gordon: Shorts (2014–2016)",
      director: "",
      duration: 15,
    },
    {
      id: "30-AdamAnderson_Moodsessions1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-AdamAnderson_Moodsessions1.mp4",
      title: "mood sessions vol. 1 by Adam Anderson",
      director: "",
      duration: 30,
    },
    {
      id: "15-ChrisRivera_3Films",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-ChrisRivera_3Films.mp4",
      title: "3 Films by Chris Rivera",
      director: "",
      duration: 15,
    },
    {
      id: "15-diamondstingily_toma",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-diamondstingily_toma.mp4",
      title: "Toma",
      director: "",
      duration: 15,
    },
    {
      id: "45-PRETXS_E01",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/45-PRETXS_E01.mp4",
      title: "PRETXS: EPISODES 1-3",
      director: "",
      duration: 45,
    },
    {
      id: "15-Gslimey_hellworld4",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-Gslimey_hellworld4.mp4",
      title: "G SLIMEY'S HELL WORLD EPISODE 4",
      director: "",
      duration: 15,
    },
    {
      id: "30-michaelwalker-33signsep3",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30-michaelwalker-33signsep3.mp4",
      title: "33 signs you’re in a simulator #3",
      director: "",
      duration: 30,
    },
    {
      id: "15-SP_BY_DRONESKY",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-SP_BY_DRONESKY.mp4",
      title: "SP by Drone Sky imagens Aereas",
      director: "",
      duration: 15,
    },
    {
      id: "15-DRONEPHOTOGRAPHY_IOANNINA",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-DRONEPHOTOGRAPHY_IOANNINA.mp4",
      title: "Drone Photography: Ioannina",
      director: "",
      duration: 15,
    },
    {
      id: "15_EVANGILLSMITH_POETA1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15_EVANGILLSMITH_POETA1.mp4",
      title: "POETA EPISODE 1: EVAN GILL SMITH",
      director: "",
      duration: 15,
    },
    {
      id: "15-JOYPRIEST_POETA2",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-JOYPRIEST_POETA2.mp4",
      title: "POETA EPISODE 2: JOY PRIEST",
      director: "",
      duration: 15,
    },
    {
      id: "15-Sarahparker_BelieveinYou",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15-Sarahparker_BelieveinYou.mp4",
      title: "Believe in You by Sarah Parker",
      director: "",
      duration: 15,
    },
    {
      id: "15_Sarahparker_Believeinyou2_1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15_Sarahparker_Believeinyou2_1.mp4",
      title:
        "Believe in You: Love yourself while facing depression by Sarah Parker",
      director: "",
      duration: 15,
    },
    {
      id: "15_Sarahparker_Believeinyou3_1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15_Sarahparker_Believeinyou3_1.mp4",
      title: "Believe in You: Friendship by Sarah Parker",
      director: "",
      duration: 15,
    },
    {
      id: "15_SarahParker_Believeinyou4_1",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/15_SarahParker_Believeinyou4_1.mp4",
      title: "Believe in You: BFF with yourself by Sarah Parker",
      director: "",
      duration: 15,
    },
    {
      id: "30_STRANGELAND_pprozack",
      link: "https://8balltv.sfo2.digitaloceanspaces.com/transcodedVideos/30_STRANGELAND_pprozack.mp4",
      title: "STRANGE LAND by @pprozack",
      director: "",
      duration: 30,
    },
  ];
</script>